In [1]:
#import libraries
import numpy as np  
import pandas as pd   
import matplotlib.pyplot as plt     
import seaborn as sns

In [2]:
#import data
#dataset loading 
df=pd.read_csv(r'C:\Users\boser\Desktop\DisasterProject\Dataset\public_emdat_custom_request_2026-03-08.csv')
display(df.sample(10))

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
157,1980-0062-IND,Yes,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25
801,2001-0011-IND,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,56.446576,"[{""adm1_code"":1505,""adm1_name"":""Punjab""},{""adm...","[{""gid_1"":""IND.28_1"",""migration_date"":""2025-12...",2003-07-01,2025-12-20
13,1928-0018-IND,Yes,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,5.482293,NaN,NaN,2003-07-01,2023-09-25
160,1980-0085-IND,Yes,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,26.270723,NaN,NaN,2003-07-01,2023-09-25
182,1983-0087-IND,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,IND,...,NaN,NaN,NaN,56000.0,176371.0,31.751200,NaN,NaN,2003-07-01,2023-09-25
456,2024-0481-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,2024-07-15,2024-07-23
336,1997-0182-IND,Yes,nat-hyd-flo-coa,Natural,Hydrological,Flood,Coastal flood,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,51.170650,NaN,NaN,2003-07-01,2023-09-25
439,2023-0234-IND,No,nat-met-ext-hea,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,97.134993,NaN,NaN,2023-04-19,2023-09-26
694,2009-9323-IND,No,nat-cli-dro-dro,Natural,Climatological,Drought,Drought,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,68.391643,"[{""adm2_code"":17576,""adm2_name"":""Barpeta""},{""a...","[{""gid_1"":""IND.34_1"",""migration_date"":""2025-12...",2009-12-08,2025-12-20
105,1972-0063-IND,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,13.330618,NaN,NaN,2003-07-01,2023-09-25

In [3]:
df.shape

(804, 47)

In [4]:
df['DisNo.'].str.split('-').str[0].shape

(804,)

In [5]:
#filtering the datasets from 1990
df2=df[df['Start Year']>=1990]
display(df2.sample(10))

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
492,2000-0610-IND,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,IND,...,NaN,NaN,NaN,691500.0,1259674.0,54.895152,"[{""adm2_code"":17946,""adm2_name"":""Barddhaman""},...","[{""gid_2"":""IND.15.22_1"",""migration_date"":""2025...",2005-09-15,2025-12-20
727,2014-0218-IND,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,GLIDE:FL-2014-000089,NaN,IND,...,NaN,NaN,NaN,2000.0,2650.0,75.468456,"[{""adm1_code"":1487,""adm1_name"":""Assam""}]","[{""gid_1"":""IND.4_1"",""migration_date"":""2025-12-...",2014-07-16,2025-12-20
391,2016-0002-IND,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2016-000001|USGS:us10004b2n,NaN,IND,...,NaN,NaN,NaN,75000.0,98025.0,76.511216,"[{""adm2_code"":17583,""adm2_name"":""Kamrup""},{""ad...","[{""gid_2"":""IND.21.1_1"",""migration_date"":""2025-...",2016-01-12,2026-01-25
294,1993-0085-IND,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,IND,...,NaN,NaN,NaN,100000.0,217148.0,46.051461,NaN,NaN,2003-07-01,2023-09-25
614,2015-0406-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,75.557977,"[{""adm2_code"":17576,""adm2_name"":""Barpeta""},{""a...","[{""gid_1"":""IND.4_1"",""migration_date"":""2025-12-...",2015-09-04,2025-12-20
419,2005-0754-IND,No,nat-bio-epi-vir,Natural,Biological,Epidemic,Viral disease,NaN,Chikungunya virus disease,IND,...,NaN,NaN,NaN,NaN,NaN,62.256479,NaN,NaN,2006-04-20,2023-09-25
588,2008-0423-IND,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,68.635672,"[{""adm1_code"":1493,""adm1_name"":""Himachal Prade...","[{""gid_1"":""IND.13_1"",""migration_date"":""2025-12...",2008-09-24,2025-12-20
684,2006-0417-IND,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,IND,...,NaN,407000.0,633317.0,3390000.0,5275047.0,64.264832,"[{""adm1_code"":1485,""adm1_name"":""Andhra Pradesh...","[{""gid_1"":""IND.11_1"",""migration_date"":""2025-12...",2007-03-09,2025-12-20
776,2008-0130-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,2000.0,2914.0,68.635672,"[{""adm1_code"":1494,""adm1_name"":""Karnataka""},{""...","[{""gid_1"":""IND.16_1"",""migration_date"":""2025-12...",2008-04-07,2025-12-20
333,1997-0124-IND,Yes,nat-hyd-mmw-lan,Natural,Hydrological,Mass movement (wet),Landslide (wet),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,51.170650,NaN,NaN,2003-07-01,2023-09-25

In [6]:
df['Latitude'].value_counts()

Latitude
15.71    2
28.50    1
23.00    1
28.70    1
32.04    1
        ..
21.03    1
26.26    1
14.13    1
26.60    1
17.43    1
Name: count, Length: 93, dtype: int64

In [7]:
#missing values
df2.isnull().sum()

DisNo.                                         0
Historic                                       0
Classification Key                             0
Disaster Group                                 0
Disaster Subgroup                              0
Disaster Type                                  0
Disaster Subtype                               0
External IDs                                 437
Event Name                                   470
ISO                                            0
Country                                        0
Subregion                                      0
Region                                         0
Location                                       1
Origin                                       316
Associated Types                             398
OFDA/BHA Response                              0
Appeal                                         0
Declaration                                    0
AID Contribution ('000 US$)                  518
Magnitude                                    350
Magnitude Scale                               62
Latitude                                     462
Longitude                                    462
River Basin                                  460
Start Year                                     0
Start Month                                    1
Start Day                                     73
End Year                                       0
End Month                                      3
End Day                                       72
Total Deaths                                  38
No. Injured                                  428
No. Affected                                 257
No. Homeless                                 482
Total Affected                               161
Reconstruction Costs ('000 US$)              544
Reconstruction Costs, Adjusted ('000 US$)    544
Insured Damage ('000 US$)                    523
Insured Damage, Adjusted ('000 US$)          523
Total Damage ('000 US$)                      389
Total Damage, Adjusted ('000 US$)            393
CPI                                           16
Admin Units                                  187
GADM Admin Units                             196
Entry Date                                     0
Last Update                                    0
dtype: int64

In [8]:
df2.shape

(544, 47)

In [9]:
df_map=df2[['Latitude', 'Longitude', 'Location', 
'Disaster Type', 'Total Deaths']].dropna(subset=['Latitude','Longitude'])

df_map.shape

(82, 5)

In [10]:
display(df_map.sample(10))

,Latitude,Longitude,Location,Disaster Type,Total Deaths
517,18.100,81.530,"Orissa, Andhra Pradesh, Chhattisgarh provinces",Flood,185.0
512,25.620,83.670,"Ballia, Chandauli districts (Uttar Pradesh pro...",Flood,130.0
587,12.730,79.700,"Andhra Pradesh, Tamil Nadu province",Flood,29.0
538,26.800,93.630,"Barpeta, Bongaigaon, Darrang, Dhemaji, Dhuburi...",Flood,21.0
514,19.730,83.750,"Andhra Pradesh, West Bengal, Bihar provinces",Storm,114.0
302,18.120,76.533,Latur area,Earthquake,NaN
720,26.376,86.240,"Barpeta, Bongaigaon, Darrang, Dhemaji, Dhuburi...",Flood,204.0
776,10.760,78.720,"Tamil Nadu, Karnataka provinces",Flood,37.0
775,22.044,94.550,"Muzaffarpur, Supaul, Patna, Katihar, Nalanda, ...",Flood,47.0
604,27.387,94.920,"Dhemaji, Tinsukia, Nagaon, Golaghat, Jorhat, K...",Flood,80.0

In [11]:
df_map.to_csv(r'C:\Users\boser\Desktop\DisasterProject\Dataset\df_map.csv')

In [12]:
df2.drop(columns=[
    'DisNo.', 'Classification Key', 'Disaster Group',
    'Historic', 'External IDs', 'Event Name',
    'OFDA/BHA Response', 'Appeal', 'Declaration',
    'ISO', 'Country', 'Region', 'Subregion',
    'Origin', 'Associated Types',
    "AID Contribution ('000 US$)",
    'No. Injured', 'No. Affected', 'No. Homeless',
    "Reconstruction Costs ('000 US$)",
    "Reconstruction Costs, Adjusted ('000 US$)",
    "Insured Damage ('000 US$)",
    "Insured Damage, Adjusted ('000 US$)",
    'CPI', 'Admin Units', 'GADM Admin Units',
    'Entry Date', 'Last Update',
    'Latitude', 'Longitude', 'River Basin'
], inplace=True)

print(df2.shape)
print(df2.columns.tolist())

(544, 16)
['Disaster Subgroup', 'Disaster Type', 'Disaster Subtype', 'Location', 'Magnitude', 'Magnitude Scale', 'Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day', 'Total Deaths', 'Total Affected', "Total Damage ('000 US$)", "Total Damage, Adjusted ('000 US$)"]

C:\Users\boser\AppData\Local\Temp\ipykernel_5636\62608353.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns=[

In [13]:
df2 = df2.sort_values(
    by=['Disaster Type','Start Year',
        'Start Month','Location'],
    na_position='last'
)

df2 = df2.drop_duplicates(
    subset=['Disaster Type','Start Year','Start Month'],
    keep='first'
)

print(df2.shape)

(408, 16)

In [14]:
df2['Start Day'] = df2['Start Day'].fillna(1)
df2['End Day'] = df2['End Day'].fillna(1)
df2['End Month'] = df2['End Month'].fillna(
    df2['Start Month'])
df2['End Year'] = df2['End Year'].fillna(
    df2['Start Year'])

df2['Start_Date'] = pd.to_datetime({
    'year'  : df2['Start Year'],
    'month' : df2['Start Month'],
    'day'   : df2['Start Day']
}, errors='coerce')

df2['End_Date'] = pd.to_datetime({
    'year'  : df2['End Year'],
    'month' : df2['End Month'],
    'day'   : df2['End Day']
}, errors='coerce')

print(df2[['Start_Date','End_Date']].head())

    Start_Date   End_Date
303 1993-03-01 1993-10-01
331 1996-03-01 1996-04-01
556 2000-04-01 2001-04-01
666 2002-07-01 2002-07-01
694 2009-07-01 2009-08-01

In [15]:
df2['Duration'] = (
    df2['End_Date'] - df2['Start_Date']
).dt.days

df2['Duration'] = df2['Duration'].fillna(1)
df2['Duration'] = df2['Duration'].clip(lower=1)

print(df2['Duration'].describe())

count    408.000000
mean      15.480392
std       49.864432
min        1.000000
25%        1.000000
50%        1.000000
75%        8.000000
max      700.000000
Name: Duration, dtype: float64

In [16]:
def get_season(month):
    if month in [6, 7, 8, 9]:
        return 'Monsoon'
    elif month in [10, 11]:
        return 'Post-Monsoon'
    elif month in [12, 1, 2]:
        return 'Winter'
    else:
        return 'Summer'

df2['Season'] = df2['Start Month'].apply(get_season)
print(df2['Season'].value_counts())

Season
Monsoon         182
Summer          103
Post-Monsoon     68
Winter           55
Name: count, dtype: int64

In [17]:
colonial_map = {
    'madras'    : 'Tamil Nadu',
    'bombay'    : 'Maharashtra',
    'calcutta'  : 'West Bengal',
    'bengal'    : 'West Bengal',
    'orissa'    : 'Odisha',
    'mysore'    : 'Karnataka',
    'bezwada'   : 'Andhra Pradesh',
    'punjab province' : 'Punjab',
    'rajputana' : 'Rajasthan',
    'saurashtra': 'Gujarat',
    'kutch'     : 'Gujarat',
}

states = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
    'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana',
    'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
    'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
    'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan',
    'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    'Delhi', 'Jammu', 'Kashmir'
]

def extract_state(location):
    if pd.isna(location):
        return 'Unknown'
    loc_lower = location.lower()
    for old, new in colonial_map.items():
        if old in loc_lower:
            return new
    for state in states:
        if state.lower() in loc_lower:
            return state
    return 'Unknown'

df2['Primary_State'] = df2['Location'].apply(
    extract_state)
print(df2['Primary_State'].value_counts().head(15))

Primary_State
West Bengal         56
Andhra Pradesh      48
Odisha              34
Assam               30
Bihar               29
Uttar Pradesh       23
Gujarat             21
Tamil Nadu          18
Unknown             18
Jammu               17
Himachal Pradesh    17
Maharashtra         16
Karnataka           10
Uttarakhand         10
Madhya Pradesh      10
Name: count, dtype: int64

In [18]:
df2['Total Deaths'] = df2[
    'Total Deaths'].fillna(
    df2['Total Deaths'].median())

df2['Total Affected'] = df2[
    'Total Affected'].fillna(
    df2['Total Affected'].median())

df2["Total Damage ('000 US$)"] = df2[
    "Total Damage ('000 US$)"].fillna(
    df2["Total Damage ('000 US$)"].median())

df2['Start Month'] = df2[
    'Start Month'].fillna(
    df2['Start Month'].mode()[0])

print(df2.isnull().sum())

Disaster Subgroup                      0
Disaster Type                          0
Disaster Subtype                       0
Location                               1
Magnitude                            263
Magnitude Scale                       58
Start Year                             0
Start Month                            0
Start Day                              0
End Year                               0
End Month                              1
End Day                                0
Total Deaths                           0
Total Affected                         0
Total Damage ('000 US$)                0
Total Damage, Adjusted ('000 US$)    295
Start_Date                             1
End_Date                               1
Duration                               0
Season                                 0
Primary_State                          0
dtype: int64

In [19]:
#LOG TRANSFORMATION ON TARGETS
df2['Deaths_log'] = np.log1p(
    df2['Total Deaths'])

df2['Affected_log'] = np.log1p(
    df2['Total Affected'])

df2['Damage_log'] = np.log1p(
    df2["Total Damage ('000 US$)"])

print(df2[['Deaths_log',
                'Affected_log',
                'Damage_log']].describe())

       Deaths_log  Affected_log  Damage_log
count  408.000000    408.000000  408.000000
mean     4.114238     10.189919   11.977087
std      1.451306      3.386121    1.161380
min      0.693147      1.609438    6.888572
25%      3.135494      8.927774   11.982935
50%      3.912023     10.308986   11.982935
75%      4.859812     11.746482   11.982935
max      9.903788     19.614603   16.588099

In [20]:
#Encoding categorical values
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in ['Disaster Type', 'Disaster Subtype',
            'Disaster Subgroup', 'Season',
            'Primary_State', 'Magnitude Scale']:
    df2[col + '_encoded'] = le.fit_transform(
        df2[col].astype(str))

print(df2.shape)

(408, 30)

In [21]:
#final check
print("Final shape:", df2.shape)
print("\nNull values remaining:")
print(df2.isnull().sum()[
    df2.isnull().sum() > 0])

df2.to_csv(
    r'C:\Users\boser\Desktop\DisasterProject\Dataset\df_cleaned.csv',
    index=False)

print("\nCleaned dataset saved successfully")

Final shape: (408, 30)

Null values remaining:
Location                               1
Magnitude                            263
Magnitude Scale                       58
End Month                              1
Total Damage, Adjusted ('000 US$)    295
Start_Date                             1
End_Date                               1
dtype: int64

Cleaned dataset saved successfully

In [23]:
df_cleaned=df2.drop(columns="Total Damage, Adjusted ('000 US$)")
df_cleaned.to_csv(
    r'C:\Users\boser\Desktop\DisasterProject\Dataset\df_cleaned_final.csv',
    index=False)