In [1]:
#import libraries
import numpy as np  
import pandas as pd   
import matplotlib.pyplot as plt     
import seaborn as sns

In [2]:
#dataset loading 
df=pd.read_csv(r'C:\Users\boser\Desktop\DisasterProject\Dataset\public_emdat_custom_request_2026-03-08.csv')
display(df.sample(10))

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
479,2020-0057-IND,No,nat-met-sto-bli,Natural,Meteorological,Storm,Blizzard/Winter storm,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,82.505684,"[{""adm1_code"":40408,""adm1_name"":""Administrativ...","[{""gid_1"":""Z06.1_1"",""migration_date"":""2025-12-...",2020-02-12,2025-12-20
709,2016-0133-IND,No,nat-met-ext-hea,Natural,Meteorological,Extreme temperature,Heat wave,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,76.511216,"[{""adm1_code"":1485,""adm1_name"":""Andhra Pradesh...","[{""gid_1"":""IND.15_1"",""migration_date"":""2025-12...",2016-05-10,2025-12-20
361,1999-0099-IND,Yes,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,IND,...,NaN,NaN,NaN,2000.0,3766.0,53.101972,NaN,NaN,2004-11-09,2023-09-25
627,2023-0548-IND,No,nat-hyd-mmw-lan,Natural,Hydrological,Mass movement (wet),Landslide (wet),NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,97.134993,"[{""adm1_code"":1502,""adm1_name"":""Mizoram""}]","[{""gid_1"":""IND.23_1"",""migration_date"":""2025-12...",2023-08-28,2025-12-20
424,2010-0694-IND,No,nat-met-sto-hai,Natural,Meteorological,Storm,Hail,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,69.513293,"[{""adm2_code"":17590,""adm2_name"":""Nalbari""}]",NaN,2011-03-17,2023-09-25
795,2001-0337-IND,No,nat-met-sto-lig,Natural,Meteorological,Storm,Lightning/Thunderstorms,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,56.446576,"[{""adm1_code"":70081,""adm1_name"":""Uttar Pradesh""}]","[{""gid_1"":""IND.34_1"",""migration_date"":""2025-12...",2003-07-01,2025-12-20
24,1949-0013-IND,Yes,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,7.585964,NaN,NaN,2003-07-01,2023-09-25
2,1907-0001-IND,Yes,nat-bio-epi-bac,Natural,Biological,Epidemic,Bacterial disease,NaN,Bubonic,IND,...,NaN,NaN,NaN,NaN,NaN,2.970490,NaN,NaN,2003-07-01,2023-09-25
94,1970-0034-IND,Yes,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,...,NaN,NaN,NaN,101200.0,817652.0,12.376910,NaN,NaN,2003-07-01,2023-09-25
670,2003-0636-IND,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,58.643553,"[{""adm1_code"":1492,""adm1_name"":""Haryana""},{""ad...","[{""gid_1"":""IND.12_1"",""migration_date"":""2025-12...",2004-01-16,2025-12-20

In [3]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     804 non-null    object
 1   Historic                                   804 non-null    object
 2   Classification Key                         804 non-null    object
 3   Disaster Group                             804 non-null    object
 4   Disaster Subgroup                          804 non-null    object
 5   Disaster Type                              804 non-null    object
 6   Disaster Subtype                           804 non-null    object
 7   External IDs                               107 non-null    object
 8   Event Name                                 96 non-null     object
 9   ISO                                        804 non-null    object
 10  Country                                    804 non-null    object
 11  Subregion                                  804 non-null    object
 12  Region                                     804 non-null    object
 13  Location                                   754 non-null    object
 14  Origin                                     229 non-null    object
 15  Associated Types                           152 non-null    object
 16  OFDA/BHA Response                          804 non-null    object
 17  Appeal                                     804 non-null    object
 18  Declaration                                804 non-null    object
 19  AID Contribution ('000 US$)                26 non-null     float64
 20  Magnitude                                  219 non-null    float64
 21  Magnitude Scale                            712 non-null    object
 22  Latitude                                   94 non-null     float64
 23  Longitude                                  94 non-null     float64
 24  River Basin                                84 non-null     object
 25  Start Year                                 804 non-null    int64
 26  Start Month                                789 non-null    float64
 27  Start Day                                  609 non-null    float64
 28  End Year                                   804 non-null    int64
 29  End Month                                  784 non-null    float64
 30  End Day                                    610 non-null    float64
 31  Total Deaths                               740 non-null    float64
 32  No. Injured                                135 non-null    float64
 33  No. Affected                               393 non-null    float64
 34  No. Homeless                               84 non-null     float64
 35  Total Affected                             509 non-null    float64
 36  Reconstruction Costs ('000 US$)            0 non-null      float64
 37  Reconstruction Costs, Adjusted ('000 US$)  0 non-null      float64
 38  Insured Damage ('000 US$)                  21 non-null     float64
 39  Insured Damage, Adjusted ('000 US$)        21 non-null     float64
 40  Total Damage ('000 US$)                    202 non-null    float64
 41  Total Damage, Adjusted ('000 US$)          198 non-null    float64
 42  CPI                                        788 non-null    float64
 43  Admin Units                                357 non-null    object
 44  GADM Admin Units                           348 non-null    object
 45  Entry Date                                 804 non-null    object
 46  Last Update                                804 non-null    object
dtypes: float64(20), int64(2), object(25)
memory usage: 295.3+ KB

None

In [4]:
df.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group',
       'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype',
       'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region',
       'Location', 'Origin', 'Associated Types', 'OFDA/BHA Response', 'Appeal',
       'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year',
       'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day',
       'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless',
       'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Reconstruction Costs, Adjusted ('000 US$)',
       'Insured Damage ('000 US$)', 'Insured Damage, Adjusted ('000 US$)',
       'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='object')

In [5]:
df.rename({
    "Total Damage ('000 US$)":"Total_Damage(USD)"
}, inplace=True)

In [6]:
df.columns

Index(['DisNo.', 'Historic', 'Classification Key', 'Disaster Group',
       'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype',
       'External IDs', 'Event Name', 'ISO', 'Country', 'Subregion', 'Region',
       'Location', 'Origin', 'Associated Types', 'OFDA/BHA Response', 'Appeal',
       'Declaration', 'AID Contribution ('000 US$)', 'Magnitude',
       'Magnitude Scale', 'Latitude', 'Longitude', 'River Basin', 'Start Year',
       'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day',
       'Total Deaths', 'No. Injured', 'No. Affected', 'No. Homeless',
       'Total Affected', 'Reconstruction Costs ('000 US$)',
       'Reconstruction Costs, Adjusted ('000 US$)',
       'Insured Damage ('000 US$)', 'Insured Damage, Adjusted ('000 US$)',
       'Total Damage ('000 US$)', 'Total Damage, Adjusted ('000 US$)', 'CPI',
       'Admin Units', 'GADM Admin Units', 'Entry Date', 'Last Update'],
      dtype='object')

### ***Objective 1- Target Columns***

In [7]:
df.shape

(804, 47)

In [8]:
df[['Total Deaths','Total Affected',"Total Damage ('000 US$)"]].info()

<class 'pandas.core.frame.DataFrame'>
Index: 804 entries, 0 to 803
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Total Deaths             740 non-null    float64
 1   Total Affected           509 non-null    float64
 2   Total Damage ('000 US$)  202 non-null    float64
dtypes: float64(3)
memory usage: 25.1 KB

In [9]:
round(df[['Total Deaths','Total Affected',"Total Damage ('000 US$)"]].describe(),2)

       Total Deaths  Total Affected  Total Damage ('000 US$)
count        740.00    5.090000e+02                   202.00
mean       12361.21    4.950835e+06                745123.20
std       128304.29    2.712715e+07               1925438.58
min            1.00    2.000000e+00                   252.00
25%           26.00    2.000000e+03                 26500.00
50%           62.00    4.000000e+04                121500.00
75%          203.25    9.000000e+05                539300.00
max      2000000.00    3.300000e+08              16000000.00